SET @business_start_ts = '%START_TS%';
SET @business_end_ts = '%END_TS%';
SET @service_start_dt = '%START_DT%';
SET @service_end_dt = '%END_DT%';

select
    ConsultId,
    AccountId,
    PrimaryId,
    GroupId,
    GroupName,
    AccountType,
    PrimaryLastName,
    PrimaryFirstName,
    PrimaryMiddleName,
    PrimaryDob,
    PrimaryGender,
    SourceHealthPlanId,
    PrimarySourceHealthPlanId,
    PatientLastName,
    PatientFirstName,
    PatientMiddleName,
    PatientDob,
    PatientGender,
    MailAddress1,
    MailAddress2,
    MailCity,
    MailState,
    MailZip,
    DiagnosisCode,
    ServiceDt,
    CptCode,
    `Modifier`,
    PlaceOfService,
    CompanyPaidAmount,
    MemberPaidAmount,
    TotalAmount,
    PayerName,
    PayerCD,
    PayerId,
    RenderingProviderId,
    RenderingProviderFirstName,
    RenderingProviderMiddleName,
    RenderingProviderLastName,
    RenderingProviderNpi,
    RenderingProviderPhone,
    RenderingProviderAddress1,
    RenderingProviderAddress2,
    RenderingProviderCity,
    RenderingProviderState,
    RenderingProviderZip,
    ConsultationState,
    ServiceSpecialty,
    CommMethod,
    BillingProviderId,
    BillingProviderName,
    BillingProviderAddressLine1,
    BillingProviderCity,
    BillingProviderState,
    BillingProviderZip,
    BillingProviderNpi,
    BillingProviderTin,
    BillingProviderPhone,
    BillingProviderEmail,
    ServiceFacilityFlg,
    RenderingProviderCd,
    Taxonomy,
    SecondaryDiagnosisCode,
    clearinghouse_cd,
    created_at,
    created_by,
    updated_at,
    updated_by,
    AccountMRNID,
    PrimaryMRNID,
    MemberId,
    PatientPhone,
    PatientEmail,
    Practice,
    BillingOrgId
FROM
    (SELECT
         consultid,
         accountmrnid AS accountid,
         primarymrnid AS primaryid,
         groupid,
         groupname,
         accounttype,
         primarylastname,
         primaryfirstname,
         primarymiddlename,
         primarydob,
         primarygender,
         sourcehealthplanid,
         primarysourcehealthplanid,
         patientlastname,
         patientfirstname,
         patientmiddlename,
         patientdob,
         patientgender,
         mailaddress1,
         mailaddress2,
         mailcity,
         mailstate,
         mailzip,
         teladoc_eds.`f_aes_decryption_serial_iv`(encrypt_diagnosiscode,NULL,'SQL','N','claim_process_log','encrypt_diagnosiscode') AS diagnosiscode,
         servicedt,
         teladoc_eds.`f_aes_decryption_serial_iv`(encrypt_cptcode,NULL,'SQL','N','claim_process_log','encrypt_cptcode') AS cptcode,
         `Modifier`,
         placeofservice,
         companypaidamount,
         memberpaidamount,
         totalamount,
         payername,
         payercd,
         payerid,
         renderingproviderid,
         renderingproviderfirstname,
         renderingprovidermiddlename,
         renderingproviderlastname,
         renderingprovidernpi,
         renderingproviderphone,
         renderingprovideraddress1,
         renderingprovideraddress2,
         renderingprovidercity,
         renderingproviderstate,
         renderingproviderzip,
         consultationstate,
         servicespecialty,
         commmethod,
         billingproviderid,
         billingprovidername,
         billingprovideraddressline1,
         billingprovidercity,
         billingproviderstate,
         billingproviderzip,
         billingprovidernpi,
         billingprovidertin,
         billingproviderphone,
         billingprovideremail,
         servicefacilityflg,
         renderingprovidercd,
         taxonomy,
         teladoc_eds.`f_aes_decryption_serial_iv`(encrypt_secondarydiagnosiscode,NULL,'SQL','N','claim_process_log','encrypt_secondarydiagnosiscode') AS secondarydiagnosiscode,
         clearinghouse_cd,
         NOW() AS created_at,
         '0' AS created_by,
         NOW() AS updated_at,
         '0' AS updated_by,
         accountmrnid,
         primarymrnid,
         memberid,
         patientphone,
         patientemail,
         practice
             ,(SELECT organization_id
               FROM teladoc_eds.billings b
                        JOIN teladoc_eds.group_billing_relations gbr ON gbr.billing_id = b.billing_id
               WHERE gbr.group_id = cpl.groupid
                 AND gbr.exclusion_cd = 'IN'
                 AND b.exclusion_cd = 'IN'
               LIMIT 1 ) AS billingorgid

     FROM
         claim.claim_process_log cpl
     WHERE business_date BETWEEN @business_start_ts AND @business_end_ts
       AND servicedt BETWEEN @service_start_dt AND @service_end_dt )z
WHERE billingorgid IS NOT NULL
ORDER BY consultid, servicedt;
